name: caso2
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend/:/usr/share/nginx/html
  database:
    env_file:
      - .env
    image: database
    container_name: database
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - 5432:5432
  proxy:
    image: proxy
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
    environment:
      - FRONT_URL=${FRONT_URL}
    depends_on:
      - frontend
      - backend
